export const acitvityTransform = {
  For: {
    shape: "For",
    name: "For_LoopCalcWaferList",
    type: "For",
    countName: "LoopLotIndex",
    counterValueList: [
      {
        name: "StartCounter",
        type: "Value",
        value: "0",
        index: "",
      },
      {
        name: "IncrementCounter",
        type: "Value",
        value: "1",
        index: "",
      },
      {
        name: "FinalCounter",
        type: "Variable",
        value: "WAFER_LIST",
        index: "arraySize",
      },
    ],
    id: "34b5d747-a437-415e-8148-8ccd1b67cfe4",
    parent: "a76d2210-2ac4-4c98-9f71-8402f164147f",
  },
  ForEnd: {
    shape: "ForEnd",
    name: "ForEnd1",
    type: "For",
    id: "34b5d747-a437-415e-8148-8ccd1b67cfe4",
    parent: "a76d2210-2ac4-4c98-9f71-8402f164147f",
  },
  Variable: {
    shape: "Variable",
    name: "Variable_DefineRecVariables",
    type: "Variable",
    parameters: [
      {
        dataType: "Value",
        type: "String",
        isArray: true,
        action: "Assign",
        name: "RecNameList",
        value: "",
      },
    ],
    id: "0e87b05c-f338-4fbc-8d07-4c1e594652d6",
  },
  IfElseEnd: {
    shape: "IfElseEnd",
    name: "IfElseEnd23",
    type: "If-else",
    id: "47cc48c0-fbb3-4321-97a9-f1a5b5a0c2cc",
    parent: "6644f311-d563-4623-b8f8-5f266f6d71fe",
  },
  IfElseCond: {
    shape: "IfElseCond",
    name: "IfElseCond_JudgeApiResultOK",
    type: "If-elseCond",
    condition: 'APIResult=="Y"',
    id: "e9b9c316-ee99-442b-951f-47b1d14016d0",
  },
  R2RStart: {
    shape: "R2RStart",
    name: "R2RStart",
    type: "R2RStart",
    outputParameters: "",
    id: "84569a5d-283d-4f8a-832d-aed638dec2e9",
  },
  R2REnd: {
    shape: "R2REnd",
    name: "R2REnd",
    type: "R2REnd",
    outputParameters: "",
    id: "13b495bb-8faf-44b7-9553-531647b74e6a",
  },
  APIFunction: {
    shape: "APIFunction",
    name: "APIFunction_GetCurChamberContext",
    type: "APIFunction",
    property: {
      apiName: "CUSTOM_ETCH_API",
      methodName: "getContext",
      returnType: "String",
      isArrayReturn: true,
      dataList: [
        {
          item: "LOT_INDEX",
          dataSource: "VARIABLES",
          dataSourcePath: "Variable_DefineLotCount",
          variable: "LotIndex",
          variableType: "Int",
          isArray: false,
        },
      ],
    },
    outputParameters: [
      {
        name: "RESULT",
        scope: "Local",
        type: "String",
        isArray: true,
      },
    ],
    id: "283827ba-e2ad-4b41-99d2-9cfba48531f0",
  },
  Allocator: {
    id: "n1",
    name: "Allocator_AssignReplyResultNG4",
    type: "Allocator",
    property: [
      {
        destination: {
          dataSource: "VARIABLES",
          dataSourcePath: "DefineVariable",
          variable: "LOT_LIST*",
          variableType: "String",
          isArray: true,
          arrayType: "CONSTANT",
        },
        source: {
          dataSource: "OUTPARAM",
          dataSourcePath: "StringString_SpiltLotArrayLOCAL",
          variable: "Result*",
          variableType: "String",
          isArray: true,
          arrayType: "CONSTANT",
        },
      },
    ],
  },
  SetupData: {
    id: "n1",
    shape: "SetupData",
    name: "SetupData1",
    type: "SetupData",

    property: {
      category: "CMP",
      schemaName: "CMP_APC_TARGET_LOT_CONFIG",
      setupKeyData: [
        {
          setupKeyItem: "CONTROLLER",
          displayName: null,
          validation: "Pass",
          dataSource: "SETUPDATA",
          dataSourcePath: "WET_FORMULA_SETTING",
          variable: "FORCE_DEFAULT",
          isArray: false,
        },
        {
          setupKeyItem: "ROUTE",
          displayName: null,
          validation: "Pass",
          dataSource: "VALUE",
          dataSourcePath: "",
          variable: "1",
        },
        {
          setupKeyItem: "RECIPE_ID",
          displayName: null,
          validation: "Pass",
          dataSource: "OUTPARAM",
          dataSourcePath: "APIFunctionAPIFunction_CreateReplyMsgLOCAL",
          variable: "RESULT",
          variableType: "String",
          isArray: false,
        },
        {
          setupKeyItem: "EQP_ID",
          displayName: null,
          validation: "Pass",
          dataSource: "VALUE",
          dataSourcePath: "",
          variable: "2",
        },
      ],
      setupSchema: [
        {
          activityUsed: false,
          childSchema: null,
          dataList: null,
          dataSql: null,
          dataTable: null,
          dataTypeCd: "BL",
          dataTypeName: "BOOLEAN",
          defaultValue: null,
          deleteFlag: false,
          description: null,
          displayName: "ForceNovaFlag",
          displayOrder: null,
          displayTypeCd: "CHK",
          displayTypeName: "CHECK",
          hideYn: false,
          hideYnStr: "N",
          inUsed: true,
          itemName: "FORCE_NOVA_FLAG",
          lowerLimit: null,
          mandatoryYn: false,
          multiYn: false,
          queryType: null,
          rawId: 1614,
          relationField: null,
          seq: 0,
          setupSchemaRawId: 602,
          skipValidationYn: "N",
          subType: null,
          subTypeName: null,
          upperLimit: null,
          validationExpress: null,
          validationMessage: null,
          validationType: null,
          validationYn: "N",
          editFlag: true,
        },
        {
          activityUsed: false,
          childSchema: null,
          dataList: null,
          dataSql: null,
          dataTable: null,
          dataTypeCd: "NM",
          dataTypeName: "NUMERIC",
          defaultValue: null,
          deleteFlag: false,
          description: null,
          displayName: "ForceNovaCount",
          displayOrder: null,
          displayTypeCd: "TXT",
          displayTypeName: "TEXT",
          hideYn: false,
          hideYnStr: "N",
          inUsed: true,
          itemName: "FORCE_NOVA_COUNT",
          lowerLimit: null,
          mandatoryYn: false,
          multiYn: false,
          queryType: null,
          rawId: 1615,
          relationField: null,
          seq: 1,
          setupSchemaRawId: 602,
          skipValidationYn: "N",
          subType: "NMI",
          subTypeName: "INT",
          upperLimit: null,
          validationExpress: null,
          validationMessage: null,
          validationType: null,
          validationYn: "N",
          editFlag: true,
        },
      ],
    },

    outputParameters: [
      {
        name: "FORCE_NOVA_FLAG",
        displayName: "ForceNovaFlag",
        scope: "Local",
        type: "String",
        isArray: false,
      },
      {
        name: "FORCE_NOVA_COUNT",
        displayName: "ForceNovaCount",
        scope: "Local",
        type: "String",
        isArray: false,
      },
    ],
  },
  String: {
    id: "n1",
    name: "String_Index",
    type: "String",
    shape: "String",
    stringInfo: {
      type: "index",
      parameterCount: 1,
      delimiter: "",
      tableData: [
        { name: "Source", type: "Value", value: "abc" },
        {
          name: "Target",
          type: "Variable",
          value: "WAFER_LIST",
          indexType: "Variable",
          index: "INT_0",
          isValueArr: true,
        },
        {
          name: "Index",
          type: "Variable",
          value: "INT_3",
          isValueArr: false,
        },
      ],
    },
    outputParameters: [
      { name: "Result", scope: "Local", type: "Int", isArray: false },
    ],
  },
};
